import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='fixed w-full z-10 top-0 m-4 bg-gray-800 text-white mb-6'>
        <NavBar />
      </div>
      <main className='mt-20'>{children}</main>
        </body>
    </html>
  )
}
